### ISSUE TITLE
Incorrect Graphql Error processing

### ISSUE THREAD

**Issue by iviaks** [mcollina/fastify-gql#106]
The current implementation of processing Graphql Errors is not compatible with [Graphql Specification](http://spec.graphql.org/June2018/#sec-Errors).

From https://github.com/rmosolgo/graphql-ruby/issues/1130#issuecomment-347373937

> It's common practice to use 200 for all GraphQL requests. When errors happen, they're put in the "errors" key. Non-200 response codes indicate that some issue occurred at the HTTP transport layer, not the GraphQL layer.

Current implementation includes next validation for 200 status code

```js
const responseSchema = {
  '2xx': {
    type: 'object',
    properties: {
      data: {
        type: 'object',
        additionalProperties: true
      },
      errors: {
        type: 'object', // <------- Problem is here. Errors should have type array
        properties: {
          message: { type: 'string' },
          locations: {
            type: 'array',
            items: {
              type: 'object',
              properties: {
                line: { type: 'integer' },
                column: { type: 'integer' }
              }
            }
          },
          path: {
            type: 'array',
            items: { type: 'string' }
          }
        }
      }
    }
  }
}
```

Also, I noticed, that `data` can't be null.

**Comment by mcollina** [comment]
Thanks for noticing this! Would you mind to send a PR to fix it?

**Comment by iviaks** [comment]
@mcollina I'm doing it! :)
