### ISSUE TITLE
Support for Automatic Persisted Queries

### ISSUE THREAD

**Issue by guigaoliveira** [mcollina/fastify-gql#110]
Some support for this feature would be interesting, which helps to improve network performance. But I don't know if there is any standardization to implement this.

About persisted queries:  "A persisted query is an ID or hash that can be sent to the server instead of the entire GraphQL query string. This smaller signature reduces bandwidth utilization and speeds up client loading times. Persisted queries are especially nice paired with GET requests, enabling the browser cache and integration with a CDN."

Interesting links: 
- [Automatic persisted queries](https://www.apollographql.com/docs/apollo-server/performance/apq/)
- [GraphQL Dynamic Persisted Queries](https://medium.com/open-graphql/graphql-dynamic-persisted-queries-eb259700f1d3)
- [Persisted Query support with Apollo Link](https://github.com/apollographql/apollo-link-persisted-queries)
- [Persisted queries in GraphQL: Slim down Apollo requests to your Ruby application](https://evilmartians.com/chronicles/persisted-queries-in-graphql-slim-down-apollo-requests-to-your-ruby-application) 
- [Relay Persisted Queries](https://relay.dev/docs/en/persisted-queries)

**Comment by mcollina** [comment]
This would be handy! What the developer workflow look like?

**Comment by ericlewis** [comment]
@mcollina from my knowledge there isn't really a set-in-stone workflow around this- it differs wildly depending on server implementation and client implementation. 

The primary idea behind it is that: at build time of the client application you "compile" or "hash" the given graphql query and then upload or store that hash somewhere else. Then, instead of sending up an entire query, the client will send an ID and if a mutation, also some data. the graphql server knows enough to match this ID with the appropriate query then runs it as usual.

The primary reasoning for this is when you have many routes, and sending up those query blobs becomes expensive. It is also good for fairly consistent latency on mobile.

**Comment by mcollina** [comment]
What is the best way to set those from your point of view? A JSON file with the query/sha combination?

**Comment by salmanm** [comment]
> at build time of the client application you "compile" or "hash" the given graphql query and then upload or store that hash somewhere else.

@ericlewis Generating a query+hash map at build time comes at the cost of maintaining a static file (or even a shares space like redis) and keeping it in sync between client and server. While it saves a little bit of processing at run-time, I think the overhead of keeping the client/server in sync isn't a good trade-off.

@mcollina @frikille 
I like how the Apollo has kinda implemented a protocol for the same, which involves specific steps that client/server both understand and there's no need to pre-inform the server about any queries.

Here's what I propose:

_Depending on whether we want this feature baked-in with a switch or available as a separate plugin_, There will be a middleware intercepting gql requests.

- By default queries would be requested by hash only
- If middleware doesn't understand, it will send a specific response
- Client will intercept the same and resend the same query to fill in server with the missing info.
- Middleware, when finds request containing a hash **and** the query, will educate itself for the subsequent calls.

The server can keep this data in an in-memory hash or in redis.

Let me know what you guys think.

I'm yet to think about how would we invalidate the queries that are no longer needed. i.e. the front-end has changed queries and old queries are stale. Let me know if you have any ideas.

**Comment by frikille** [comment]
Thanks @salmanm  to picking this up!

After discussion with @mcollina we agreed that as a first version it would be better to have support for persistent queries via a JSON file (or it can be a function that loads the data from a remote location).

**Comment by pscarey** [comment]
@mcollina Thanks for merging the PR & working to get it over the line.

I believe this issue can be closed now, as there is full support for a range of persisted queries implementations?

**Comment by mcollina** [comment]
Yes you are right! Good job!
