### ISSUE TITLE
Using a sub-property

### ISSUE THREAD

**Issue by wale-A** [mcollina/fastify-gql#123]
In graphQL, it is possible to go create an object like this
```js
const AuthorType = new GraphQLObjectType({
    name: 'Author',
    fields: ( ) => ({
        id: { type: GraphQLID },
        name: { type: GraphQLString },
        age: { type: GraphQLInt },
        books: {
            type: new GraphQLList(BookType),
            resolve(parent, args){
                return Book.find({ authorId: parent.id });
            }
        }
    })
});
```

now with fastify-gql, i'm also trying to do something like that, i know the data types are different, but i don't know how to add a resolver to the dependent property
```js
type AuthorType {
        id: Int,
        name:String,
        age: Int,
        books: {
            type: [BookType],
            resolve(parent, args){
                return Book.find({ authorId: parent.id });
            }
        }
    })
}
```
i've tried doing something like the above (i didn't think it'd work but i wanted to try it)..it didn't.

my issue now is, how do i go about creating a resolver for the dependent property.

**Comment by mcollina** [comment]
please upload a full example

**Comment by wale-A** [comment]
`
import { Adhesive, Thickness } from './dbSchema'
import { BaseRepo } from '../repo/repoBase'
import { ShapeRepo } from '../repo/shapeRepo'

export const schema = `
  type Thickness {
    code: String,
    name: String
  }

  type Adhesive {
    code: String,
    name: String
  }

  type ShapeLevelThickness {
    adhesive: Adhesive,
    thickness: [String]
  }

  type Shape {
    code: String,
    name: String,
    image: String,
    adhesives: {
      type: [Adhesive],
      resolve(_, args){
        const repo = new BaseRepo<Adhesive>(Adhesive)
        const result = repo.tryGetOneWithCode(args.code)
        return result
      }
    },
    thickness: [ShapeLevelThickness]
  }

  type Query {
    allThickness: [Thickness],
    thickness(code: String!): Thickness,
    allAdhesive: [Adhesive],
    adhesive(code: String!): Adhesive,
    allShape: [Shape],
    shape(code: String!):Shape
  }

  type Mutation {
    createThickness(name: String!, code: String!): Thickness
  }
`

export const resolvers = {
  Query: {
    async allThickness() {
      const repo = new BaseRepo<Thickness>(Thickness)
      return await repo.getAll()
    },
    async thickness(_: any, data: any) {
      console.log('----------------------------------')
      console.log(_)
      const repo = new BaseRepo<Thickness>(Thickness)
      const result = repo.tryGetOneWithCode(data.code)
      return result
    },
    async allAdhesive() {
      const repo = new BaseRepo<Adhesive>(Adhesive)
      return await repo.getAll()
    },
    async adhesive(_: any, data: any) {
      const repo = new BaseRepo<Adhesive>(Adhesive)
      const result = repo.tryGetOneWithCode(data.code)
      return result
    },
    async allShape() {
      const repo = new ShapeRepo()
      return await repo.getAll()
    },
    async shape(_: any, data: any) {
      const repo = new ShapeRepo()
      return await repo.tryGetOneWithCode(data.code)
    }
  },

  Mutation: {
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    async createThickness(_: any, thickness: Thickness) {
      const repo = new BaseRepo<Thickness>(Thickness)
      const result = await repo.insert([thickness])
      return result[0]
    }
  }
}
`

**Comment by mcollina** [comment]
This should do the trick, however that is hard to know because I cannot run that:

```js
import { Adhesive, Thickness } from './dbSchema'
import { BaseRepo } from '../repo/repoBase'
import { ShapeRepo } from '../repo/shapeRepo'

export const schema = `
  type Thickness {
    code: String,
    name: String
  }

  type Adhesive {
    code: String,
    name: String
  }

  type ShapeLevelThickness {
    adhesive: Adhesive,
    thickness: [String]
  }

  type Shape {
    code: String,
    name: String,
    image: String,
    adhesives: {
      type: [Adhesive]
    },
    thickness: [ShapeLevelThickness]
  }

  type Query {
    allThickness: [Thickness],
    thickness(code: String!): Thickness,
    allAdhesive: [Adhesive],
    adhesive(code: String!): Adhesive,
    allShape: [Shape],
    shape(code: String!):Shape
  }

  type Mutation {
    createThickness(name: String!, code: String!): Thickness
  }
`

export const resolvers = {
  Query: {
    async allThickness() {
      const repo = new BaseRepo<Thickness>(Thickness)
      return await repo.getAll()
    },
    async thickness(_: any, data: any) {
      console.log('----------------------------------')
      console.log(_)
      const repo = new BaseRepo<Thickness>(Thickness)
      const result = repo.tryGetOneWithCode(data.code)
      return result
    },
    async allAdhesive() {
      const repo = new BaseRepo<Adhesive>(Adhesive)
      return await repo.getAll()
    },
    async adhesive(_: any, data: any) {
      const repo = new BaseRepo<Adhesive>(Adhesive)
      const result = repo.tryGetOneWithCode(data.code)
      return result
    },
    async allShape() {
      const repo = new ShapeRepo()
      return await repo.getAll()
    },
    async shape(_: any, data: any) {
      const repo = new ShapeRepo()
      return await repo.tryGetOneWithCode(data.code)
    }
  },

  Mutation: {
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    async createThickness(_: any, thickness: Thickness) {
      const repo = new BaseRepo<Thickness>(Thickness)
      const result = await repo.insert([thickness])
      return result[0]
    }
  }
}
```

**Comment by wale-A** [comment]
yh, sorry about that. i'm not sure you understand what i'm trying to do.

i'm trying to create a resolver for the 'adhesives' property....so i can just get the full values of the adhesives from the db.

like in the image below

![image](https://user-images.githubusercontent.com/10295167/74446715-97eaa200-4e78-11ea-9beb-b85e547ba30f.png)

**Comment by mcollina** [comment]
This should do what you need: https://github.com/mcollina/fastify-gql/blob/master/test/query-depth.js#L8-L87.

**Comment by wale-A** [comment]
I honestly apologize for the stress.
I just looked through the fastify-gql package and what i wanted is what you referred to as *loaders*.

i was able to solve my own problem

![image](https://user-images.githubusercontent.com/10295167/74449271-a33fcc80-4e7c-11ea-8ab0-1c449854857b.png)

**Comment by mcollina** [comment]
I would recommend to avoid the queries.map and define a single database operation to get them all. Otherwise loaders would be useless.
