### ISSUE TITLE
Got 500 error: Unexpected end of JSON input

### ISSUE THREAD

**Issue by LILU-WEB** [mcollina/fastify-gql#124]
Hi 
I use throw new Error("XXXX"), however looks like i got a 500 error for first requst everytime when program start,  but the next requst is OK (i got 200 reponse for next time, the same request, the same error message without 500 error, shows username or password is wrong)
the error message shows something wrong from index.js:299:19... guys any idea for this?

I'm a newbie, please suggestions, thanks 

My version: "fastify-gql": "^3.0.6",

server started at "http://localhost:3000/playground.html
InternalServerError: Internal Server Error
    at Object.fastifyGraphQl [as graphql] (D:\javascript\alpha\node_modules\fastify-gql\index.js:299:19)
    at processTicksAndRejections (internal/process/task_queues.js:93:5) {
  message: 'Internal Server Error',
  errors: [
    Error: input username or password is wrong
        at userResolver.hello (D:\javascript\alpha\src\module\user\userResolver.ts:35:15)
        at Object.<anonymous> (D:\javascript\alpha\node_modules\type-graphql\dist\resolvers\create.js:16:64)
        at Generator.next (<anonymous>)
        at fulfilled (D:\javascript\alpha\node_modules\tslib\tslib.js:107:62)
        at processTicksAndRejections (internal/process/task_queues.js:93:5) {
      message: 'input username or password is wrong',
      locations: [Array],
      path: [Array]
    }
  ],
  data: null
}

**Comment by mcollina** [comment]
I don’t understand what is the question. Would you mind to upload a full runnable example to reproduce your problem?

It seems the problem is in your resolver.

**Comment by LILU-WEB** [comment]
Thank you so much for reply.

I did some research, looks its the problem in resolver. I use the lastest type-graphql.. i found code "throw new error" in resolver doesnt trigger setErrorHandler in fasitfy-gql except the first visit. The first hello query is 500 error due to something wrong, show "Unexpected end of JSON" and if i try to hello query again, it works and respond 200.  It makes me so confusing..any suggestions? please.

![image](https://user-images.githubusercontent.com/61072803/74584442-5b9c7a80-500d-11ea-93c9-187a2b32aaa3.png)


Resolver.ts
`
    @Query(returns => String)
    async hello() {
        throw new Error("xxxxxx");
    }`

Index.ts
`    app.register(GQL, {
        schema,
        graphiql: 'playground',
        jit: 1,
        errorHandler: setErrorHandler
    });

const setErrorHandler = (async (error: any, req: any, reply: any) => {
    console.log(error);
    reply.send()
})
`

**Comment by mcollina** [comment]
As I said, I would need a *full runnable example to reproduce your problem* in JavaScript. Something similar to https://github.com/mcollina/fastify-gql/blob/master/examples/basic.js.

**Comment by LILU-WEB** [comment]
Here you are.. please remember to reStart or reRun program before try query hello
https://github.com/LILU-WEB/askforhelp/blob/master/index.ts

**Comment by mcollina** [comment]
Can you please add the required dependencies and a command to run the typescript file. Thanks.

**Comment by LILU-WEB** [comment]
Hi 
i use yarn...  run command: yarn start, i upload package.json and others files, project structor:
-------------------
src/index.ts
package.json
tsconfig.json
tslint.json
----------------------   
package.json
https://github.com/LILU-WEB/askforhelp/blob/master/package.json
tsconfig.json
https://github.com/LILU-WEB/askforhelp/blob/master/tsconfig.json
tslint.json
https://github.com/LILU-WEB/askforhelp/blob/master/tslint.json

**thank you so much for the help**~~

**Comment by LILU-WEB** [comment]
opss~~ After couple of hours research, i found this is not fastify-gql issue at all, it‘s the problem in type-graphql error message.

For onlyone who have the same issue intergrity with type-graphql and wants customize error message by HTTP response status codes.

for example: my error message is  400: xxxxxxxxxxx

1. use type-graphql globalMiddleware
`globalMiddlewares: [errorMiddleware]`

2. greate a middleware
```javascript
export class errorMiddleware implements MiddlewareInterface<any> {
    constructor() { }
    async use({ context, info }: ResolverData<any>, next: NextFn) {
        try {
            return await next();
        } catch (err) {
            let parts = err.message.split(':');
            if (parts.length == 2) {
                context.reply.code(parts[0])
            }
            throw err;
        }
    }
}
```

3. check the reply code and error message.
![image](https://user-images.githubusercontent.com/61072803/74590560-80fba980-504a-11ea-9971-13ff5c0665c6.png)

I'm junier please let me know if you have a better way to achieve this, thanks
