### ISSUE TITLE
Issue with Query Depth - Bad Request in Playground

### ISSUE THREAD

**Issue by dougg0k** [mcollina/fastify-gql#134]
Hello!

If I try to set queryDepth, the /graphql endpoint no longer load in the Playground, I get an Bad Request error.

It's a infinite loading with repeated errors. 
```
BadRequestError: Bad Request
        at Object.fastifyGraphQl [as graphql] (/node_modules/fastify-gql/index.js:300:23)
        at _Reply.graphql (/node_modules/fastify-gql/index.js:129:16)
        at Object.<anonymous> (/node_modules/fastify-gql/lib/routes.js:215:18)
        at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

**Comment by mcollina** [comment]
Are you passing any specific option to fastify-gql? Which version where you running before it stopped working?

**Comment by mcollina** [comment]
Is `// queryDepth: 5` that is causing the error?

**Comment by dougg0k** [comment]
Yes, only in the IDE, if I try to POST query outside IDE, it works.

**Comment by frikille** [comment]
I think it is because the playground runs an introspection query when it starts up. And the introspection query fails the query depth validation and the query is rejected. However the playground keeps sending the same query until it gets a response, that's why it is an infinite loop.
