### ISSUE TITLE
Support non-default path in Playground

### ISSUE THREAD

**Issue by orthimnas** [mcollina/fastify-gql#138]
First, thanks for the great library - it is amazing.

I've noticed that when I use the `path` property when registering `fastifyGql` that the playground can no longer post successfully.  It appears that the route in the `Playground.html` is hard coded to `/graphql` - the default path.  Can this be updated to use the path specified when registering `fastifyGql`?

Example:
```js
const app: fastify.FastifyInstance<
  Server,
  IncomingMessage,
  ServerResponse
> = fastify({});
...
app.register(fastifyGql, {
  schema,
  context,
  jit: 1,
  graphiql: 'playground',
  path: '/fargate/graphql',
});
```

Hard coded endpoint in [playground](https://github.com/mcollina/fastify-gql/blob/master/static/playground.html#L57):
```html
window.addEventListener('load', function(event) {
  GraphQLPlayground.init(document.getElementById('root'), {
	subscriptionEndpoint: '/graphql',
	endpoint: '/graphql',
  });
});
```

**Comment by mcollina** [comment]
I think this might require some rework of how we serve the files, but it'd definitely be a good addition. Would you like to send a PR?
