### ISSUE TITLE
Load schema based upon request url parameter 

### ISSUE THREAD

**Issue by RenatoFranze** [mcollina/fastify-gql#141]
Hi, 

First of all, thanks for this plugin and this is not a bug report or a sugestion, hehe!

Can anyone help me with this scenario:
I would like to make an universal route in fastify with an url parameter. Based upon this parameter, my route loads the specific graphql schema and only after that, exposes the graphql/graphqli interface. Is it possible?

Example:
- Route is localhost/a/:name/graphql
- Request made to localhost/a/aaaa/graphl
- Route loads 'aaaa' graphql schema and initialize fastify-gql

Thanks!

**Comment by mcollina** [comment]
I don't think this is possible right now. However you could have a preHandler hook to return an early 404 in case it is disabled.

I don't understand the usecase anyway, so I would love to know more.

**Comment by RenatoFranze** [comment]
Hi @mcollina , thanks for answering.

Basically, I have this:

- I work at a company that each costumer has his own mysql database. 
- I'm using a library (graphcraft) that dinamically converts Sequelize models into Graphql schema.

So, the ideia behind an url parameter is to tell me which database should I connect using Sequelize,  and, with graphcraft, creates the right schema for Graphql works properly.

**Comment by mcollina** [comment]
Unfortunately, I don't think this library would support you well. It assumes the schema does not change during the lifetime of a server.

I would also recommend to rethink some part of your architecture because what you propose would not perform well both for latency and scalability.

**Comment by asciidisco** [comment]
@RenatoFranze It does sound like an unusual usecase, definitely. You're probably better off with using a dedicated `http` server (you can use `fastify` for this) & roll your own GraphQL response/request handler.

You can have [a look here](https://github.com/benawad/node-graphql-benchmarks/blob/master/benchmarks/core-graphql-jit-str.js), how you could even do that with `graphql-jit` support, if performance was your concern & the reason you wanted to use fastify-gql.
You just need to swap out the schema generation with the one you use & then reply with the one based on your url parameter.

That being said, I think this could be closed //cc @mcollina
