### ISSUE TITLE
Consider adding graphql-tools as a dependency

### ISSUE THREAD

**Issue by tHBp** [mcollina/fastify-gql#142]
Typescript build fails if the project is using `fastify-gql` without `graphql-tools` [because of this line](https://github.com/mcollina/fastify-gql/blob/6ccf69519bc30effb467dab69551b34378860cb3/index.d.ts#L3).

A workaround is using `--skipLibCheck` with `tsc`, but it beats the purpose of using Typescript, in my opinion.

Requesting to add it as a dependency rather than devDependency or mark it as a peer dependency and update the docs accordingly.

I'd be happy to raise a PR, if change is considered.

Thanks.

**Comment by mcollina** [comment]
We don't use graphql-tools internally, so I don't know why it is in the types. The right PR is to embed that type in here. Would you mind to send a PR to get that done?

**Comment by tHBp** [comment]
My bad, didn't get a chance to raise a PR. Glad the issue got resolved.
