### ISSUE TITLE
A method to throw Bad Request (400) errors by using `throw` inside resolvers

### ISSUE THREAD

**Issue by yndc** [mcollina/fastify-gql#143]
I can't find a way to throw `Bad Request (400)` errors from resolvers to indicate that the error is caused by the client sending bad or invalid input data (I need a way to indicate whether the error is coming from a server issue or invalid input data). At the moment `throw`s inside resolvers will return `Internal Server Error (500)` errors.

Coming from Apollo, I could use their customized errors (`UserInputError` for bad request errors and `ApolloError` for server errors) to accomplish this. Is there any way to achieve the same in `fastify-gql`?

**Comment by mcollina** [comment]
You should be able to use all of https://www.npmjs.com/package/http-errors. Let us know if it worked well for you.

**Comment by yndc** [comment]
I tried using that package but got the same result (`500 Internal Server Error`).

I found these lines that causes all errors to be thrown as `InternalServerError`.
https://github.com/mcollina/fastify-gql/blob/6ccf69519bc30effb467dab69551b34378860cb3/index.js#L363-L368

If I changed the hard-coded error instance creation to:
```js
const err = execution.errors[0].originalError
```

Throwing errors from resolvers using `http-errors` works really well.  

```js
throw createError(401, "unauthorized error")
```
Response result:
```js
{
  statusCode: 401,
  data: null,
  errors: [
    {
      message: 'unauthorized error',
      locations: [Array],
      path: [Array]
    }
  ]
}
```

But I don't feel right using the errors first element from GraphQL execution result (`execution.errors[0]`). I just realized that in GraphQL you can have multiple exceptions (or errors) in one query. For example:

```
{
    someQuery1 { ... } // throw Unauthorized exception
    someQuery2 { ... } // throw Forbidden exception
}
```

In that example I don't think it's correct to alter the response HTTP code. I didn't find anything related to HTTP status codes in the GraphQL spec. Perhaps my original approach was wrong.

**Comment by yndc** [comment]
I just found something interesting.

Seems like using `throw` inside resolvers with `fastify-gql` would stop the execution of the whole query. 

In this example, I've made a simple schema: 
```
type Query {
    throw1: String!
    throw2: String!
}
```
In the resolvers, `throw1` query would throw `BadRequest` exception, while `throw2` query would throw `Forbidden` exception.

Here's the code using `graphql-js` library:

```js
const gql = require("graphql");
const createError = require("http-errors");

const schema = new gql.GraphQLSchema({
  query: new gql.GraphQLObjectType({
    name: "RootQueryType",
    fields: {
      throw1: {
        type: gql.GraphQLString,
        resolve() {
          console.log("run 1");
          throw createError(401, "throw1 error");
        },
      },
      throw2: {
        type: gql.GraphQLString,
        resolve() {
          console.log("run 2");
          throw createError(403, "throw2 error");
        },
      },
    },
  }),
});

gql.graphql(schema, `{ throw1, throw2 }`).then((result) => {
  console.log(result.errors);
});
```

When run, both resolvers were executing and two errors were thrown: 

```
yondercode:~/toys/gqltest$ node index.js 
run 1
run 2
[
  UnauthorizedError: throw1 error
      at resolve (/home/yondercode/toys/gqltest/index.js:12:17)
      at resolveFieldValueOrError (/home/yondercode/toys/gqltest/node_modules/graphql/execution/execute.js:486:18)
      at resolveField (/home/yondercode/toys/gqltest/node_modules/graphql/execution/execute.js:444:16)
      at executeFields (/home/yondercode/toys/gqltest/node_modules/graphql/execution/execute.js:281:18)
      at executeOperation (/home/yondercode/toys/gqltest/node_modules/graphql/execution/execute.js:225:122)
      at executeImpl (/home/yondercode/toys/gqltest/node_modules/graphql/execution/execute.js:102:14)
      at execute (/home/yondercode/toys/gqltest/node_modules/graphql/execution/execute.js:62:35)
      at graphqlImpl (/home/yondercode/toys/gqltest/node_modules/graphql/graphql.js:108:31)
      at /home/yondercode/toys/gqltest/node_modules/graphql/graphql.js:28:59
      at new Promise (<anonymous>) {
    message: 'throw1 error',
    locations: [ [Object] ],
    path: [ 'throw1' ]
  },
  ForbiddenError: throw2 error
      at resolve (/home/yondercode/toys/gqltest/index.js:19:17)
      at resolveFieldValueOrError (/home/yondercode/toys/gqltest/node_modules/graphql/execution/execute.js:486:18)
      at resolveField (/home/yondercode/toys/gqltest/node_modules/graphql/execution/execute.js:444:16)
      at executeFields (/home/yondercode/toys/gqltest/node_modules/graphql/execution/execute.js:281:18)
      at executeOperation (/home/yondercode/toys/gqltest/node_modules/graphql/execution/execute.js:225:122)
      at executeImpl (/home/yondercode/toys/gqltest/node_modules/graphql/execution/execute.js:102:14)
      at execute (/home/yondercode/toys/gqltest/node_modules/graphql/execution/execute.js:62:35)
      at graphqlImpl (/home/yondercode/toys/gqltest/node_modules/graphql/graphql.js:108:31)
      at /home/yondercode/toys/gqltest/node_modules/graphql/graphql.js:28:59
      at new Promise (<anonymous>) {
    message: 'throw2 error',
    locations: [ [Object] ],
    path: [ 'throw2' ]
  }
]
```

Meanwhile this is the `fastify-gql` code for the same kind of program:
```js
const createError = require("http-errors");
const fastify = require("fastify");
const fastifyGql = require("fastify-gql");

const server = fastify();

server.register(fastifyGql, {
  schema: `
  type Query {
    throw1: String!
    throw2: String!
  }
  `,
  resolvers: {
    Query: {
      throw1: () => {
        console.log("run 1");
        throw createError(401, "throw1 error");
      },
      throw2: () => {
        console.log("run 2");
        throw createError(403, "throw2 error");
      },
    },
  },
});

server
  .inject({
    method: "POST",
    url: "/graphql",
    payload: {
      query: `{ throw1, throw2 }`,
    },
  })
  .then((response) => {
    console.log(response.payload);
  });
```
When run, only the first resolver were executed and only one error were thrown.
```
yondercode:~/toys/gqltest$ node server.js 
run 1
{"errors":[{"message":"throw1 error","locations":[{"line":1,"column":3}],"path":["throw1"]}],"data":null}
```
Is there a mistake on my code or maybe I should open a new issue and close this one (since what I wanted to do originally doesn't seems to be correct in GraphQL)? Thanks.

**Comment by mcollina** [comment]
GraphQL does not follow the REST pattern, as far as I know.

**Comment by yndc** [comment]
Yes that's right, I think the current implementation is more logical and my original intention isn't. `Internal Server Error` should be the response when the server is unable to return a value to a field that is not nullable. I'm closing this now, thanks!
