### ISSUE TITLE
Enable building context for subscriptions

### ISSUE THREAD

**Issue by bvanneerven** [mcollina/fastify-gql#151]
This issue looks like a duplicate of #47 (which is already implemented :tada: ), but differs because it requests adding a similar API to allow building the `SubscriptionContext` instead of the context for queries/mutations.

A possible way of doing this would be like:

```js
app.register(GQL, {
  schema,
  resolvers,
  subscription: {
      // This would add { foo: "bar" } to the SubscriptionContext, such that it is 
      // available in subscription resolvers
      context: () => ({ foo: "bar"})
  }
})
```

The main use case for this, in my case, is creating the possibility to subscribe to user-specific content. That is, when a client sends a subscription query and includes an `Authorization` header, we populate the `SubscriptionContext` with the user information extracted from the Bearer token and use that in the subscription resolver to send updates only to that user.

```js
// server.js
app.register(GQL, {
  schema,
  resolvers,
  subscription: {
      context: (req) => ({ user: jwt.verify(req.headers["Authorization"].slice(7))})
  }
})


// resolvers.js
const resolvers = {
  Mutation: {
    sendMessage: async (_, { message, user }, { pubsub }) => {
      await pubsub.publish({
        topic: user.id,
        payload: message
      })

      return "OK"
    }
  },
  Subscription: {
    receivedMessage: {
      subscribe: (root, args, { pubsub, user }) => pubsub.subscribe(user.id)
    }
  }
}
```

I have not yet found an intuitive way to support this use case, which is why I am submitting this issue. However, since fastify is still new to me, I could be the problem too :sweat_smile:. If that is the case, I'd be happy to add the solution to the docs if someone can point me in the right direction!

**Comment by mcollina** [comment]
It would be great to add support for this!

@frikille what do you think?

**Comment by frikille** [comment]
I think it's a good idea and should be implemented (I looked into it earlier today if the `options.context` function is passed to the subscription, but no, it's not).

I think the main question is whether we want to add a separate context builder function or re-use the one that can be already set in the plugin options.

**Comment by mcollina** [comment]
Would the API be different?

**Comment by bvanneerven** [comment]
Very cool that you guys are willing to add this functionality! :smiley:. I went ahead and created a first prototype for this in #153.

**Comment by asciidisco** [comment]
Closing as it has been merged in https://github.com/mcollina/fastify-gql/pull/233
