### ISSUE TITLE
Subscription client authentication

### ISSUE THREAD

**Issue by PacoDu** [mcollina/fastify-gql#166]
What is the recommended authentication flow for subscription ? 
The documentation suggest:
```js
verifyClient: (info, next) => {
      if (info.req.headers['x-fastify-header'] !== 'fastify is awesome !') {
        return next(false) // the connection is not allowed
      }
      next(true) // the connection is allowed
    }
```

But it's not possible to add custom headers to the websocket http request from a browser (see: https://stackoverflow.com/questions/4361173/http-headers-in-websockets-client-api/41521871 and https://github.com/apollographql/apollo-client/issues/3967). So basically it's not possible to authenticate an incoming connection from a browser with verifyClient except with a cookie header.

Apollo uses a onConnect method to validate the `connection_init` payload send by client that contains the authentication infos.

**Comment by mcollina** [comment]
Good spot. Would you like to send a PR that add that support?
