### ISSUE TITLE
Question/Request: errorHandler

### ISSUE THREAD

**Issue by dougg0k** [mcollina/fastify-gql#169]
Hi,

Is there a way build a more specific errors array? 

It seems that anything returned to `error` argument from `errorHandler` are very strict to the exact graphql specs which doesn't seem very useful in some cases, it returns pointless information that it's not necessary in the frontend.

A good example, `locations` and `path` has no use, only `message`, and I cannot get more details that would make things easier when consuming the API. Unless I am doing something wrong, and I am just throwing errors, I get this message and no other objects in the `errors` array, maybe it's a bug, not entirely sure.
```
"errors": [
    {
      "message": "4 errors occurred",
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ],
      "path": [
        "changePassword"
      ]
    }
  ]
```

Would be cool to be able to easily return a custom object in the errors array similarly to:
https://miro.medium.com/max/1400/1*vVpmJHSUKPz-SIno_0Z9Pg.png

It has a more clear intent rather than returning useless information. 

Before starting with `fastify-gql`, I was able to do this with `apollo-server`, would be cool to be able to do the same with `fastify-gql`.

**Comment by mcollina** [comment]
I'm not really sure how that will be implemented here. Note that we are somewhat limited to what graphql-jit can do. Would you like to give it a go and send a PR?

**Comment by dougg0k** [comment]
Hm, I understand. If I get the time, I will let you know.

**Comment by dougg0k** [comment]
I actually solved this another way.

By using `ErrorWithProps` from `fastify-gql`, I sent the the object in the extensions and just modified the response.

```
app.addHook("onSend", (request, reply, payload, done) => {
	const payloadParsed = JSON.parse(payload);
	if (!!payloadParsed.errors && payloadParsed.errors.length > 0) {
		const errors = payloadParsed.errors.map((err) => ({
			code: err.extensions.code,
			message: err.extensions.message,
		}));
		payloadParsed.errors = errors;
	}
	done(undefined, JSON.stringify(payloadParsed));
});
```

**Comment by lewispham** [comment]
I think this issue should be reopen as there is still no official solutions. We can have a workaround via adding a `postExecution` hook for parsing the error response. This hook should be executed right after the resolvers. Right now with the `onResolution` hook, we can only access the parsed errors, not the original ones.

**Comment by muco-rolle** [comment]
In the apollo server there's `apollo-error` do we have something similar in Mercurius?
