### ISSUE TITLE
Error propagation/serialization when using Gateway mode

### ISSUE THREAD

**Issue by asciidisco** [mcollina/fastify-gql#171]
## Situation

I've added a new resolver to the `lib/gateway.js` example, in addition to the `me` resolver
there's now also a `you` resolver that looks like this:

```js
Query: {
  // ...
  you: (root, args, context, info) => {
    throw new ErrorWithProps(`Can't fetch other users data`, { code: 'NOT_ALLOWED' })
  },
  // ...
},
```

I've, of course, also extended the schema:

```js
  await createService(4001, `
    extend type Query {
      me: User
      you: User
      hello: String
    }
    // ...`
```

## Expectation

I've looked for a common pattern/specification on how a federated service should deal with these kind of errors,
which are being propagated from a federated service, via the gateway, to a client. But either my "google-foo" has become weak,
or there is just nothing out there describing what should happen in this case.

My personal expectation would be, that errors from a federated services would be collected by the gateway & propagated "as is" as part of the `errors` property of the final response which is being dispatched from the gateway to the client.
Taking the example from above, I'd expect to see the following as the result of calling the gateway with this query:

```
{
  you {
    id
    name
  }
}

```

```json
{
  "data": {
    "me": null
  },
  "errors": [
    {
      "message": "Can't fetch other users data",
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ],
      "path": [
        "you"
      ],
      "extensions": {
        "code": "NOT_ALLOWED"
      }
    }
  ]
}
```

## Problem

Unfortunately that's not the case, even worse, I'll get different results when running the query for the first time (e.g. non jit'ed),
and for subsequent runs (when graphql-jit kicked in):

### Non jit'ed result

```json
{
  "data": {
    "you": null
  },
  "errors": [
    {
      "message": "Unexpected error value: [{ message: \"Can't fetch other users data\", locations: [Array], path: [Array], extensions: [Object] }]",
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ],
      "path": [
        "you"
      ]
    }
  ]
}
```

### Result of subsequent runs with active graphql-jit

```json
{
  "data": {
    "you": null
  },
  "errors": [
    {
      "message": "[object Object]",
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ],
      "path": [
        "you"
      ]
    }
  ]
}
```

## Reason behind this behaviour

`graphql` expects an error (or a rejected result) to be an instance of `Error`; see https://github.com/graphql/graphql-js/blob/74ce729eddf7c777a1c500d63f1c4fce35e9f1cf/src/execution/execute.js#L683-L720

Otherwise it converts it to an error on its own `return new Error('Unexpected error value: ' + inspect(error));`, while `inspect` serializes the error to a string, stripping out all other defined fields. `fastify-gql` on the other hand just `rejects` in an error case with the raw `json.errors` array, triggering the unfortunate serialization behaviour that way; see https://github.com/mcollina/fastify-gql/blob/master/lib/gateway/request.js#L92

Interestingly, `graphql-jit` is happy if https://github.com/mcollina/fastify-gql/blob/master/lib/gateway/request.js#L92 would reject with an array of `GraphQLError` instances (I first tried to apply the mapping there), responding with the desired result, but `graphql` does not like anything except something extending `Error`, and still producing a badly serialized result.

## Solution (well, kind of)

I've forked `fastify-gql` and added a branch with the changes that lead to my desired result (with comments for each change), but I guess it might be helpful to walk through them one by one.

* As `graphql` doesn't cope well with errors not extending the built-in `Error`, I've added a `FederatedError` (https://github.com/asciidisco/fastify-gql/blob/fix/federated-error-propagation/lib/errors.js#L23) that holds the errors array from the response of the federated service as a property (https://github.com/asciidisco/fastify-gql/blob/fix/federated-error-propagation/lib/gateway/request.js#L95)

* I've modified the `defaultErrorHandler` so that an instance of a `FederatedError` can be flattened into a list of actual errors happened at the service level (https://github.com/asciidisco/fastify-gql/blob/fix/federated-error-propagation/lib/routes.js#L61-L74). As the original location of the error can't be mapped easily when creating a new `GraphQLError` (at least I had no success in doing so) and the `locations` property of a `GraphQLError` is read-only, I'm constructing a new error that just takes the original error values and inherits the prototype of `GraphQLError` to satisfy subsequent checks (https://github.com/asciidisco/fastify-gql/blob/698d31c1bc616cb54aef4388a8eeb61dae205c05/lib/errors.js#L35-L69)

* As `graphql-jit` isn't aware of our mapping in the `defaultErrorHandler` (also wan't sure here if it's intentional that the `defaultErrorHandler` isn't invoked in case we have a jit'ed result), we have to apply a similar transformation before sending the jit'ed result (https://github.com/asciidisco/fastify-gql/blob/fix/federated-error-propagation/index.js#L370-L380)

* To validate the solution, I've added the `you` query mentioned above to `examples/gateway`. (https://github.com/asciidisco/fastify-gql/blob/fix/federated-error-propagation/examples/gateway.js#L87-L89)

## Why not a PR right away?

* First of all, I'm not sure if I'm missing something obvious here (just started out with fastify-gql), so it could be very well that this is a problem on my side, missing how to properly propagate issues from a federated service, via the gateway, to the client

* As there seems to be no spec around this, I'm not sure if my desired result/expectation matches with what other users need/want. Therefore I believe there should be a discussion first, to define the desired outcome

* My solution does not seem very PR'able to me. Aside from missing tests & docs (which I would add if it would come to a PR): I'm absolutely not happy with my solution, codewise. It seems to work (produce my desired result), but the modifications I've made to the codebase do not seem ideal to me (nonetheless, I wasn't able to find a more elegant way to achieve the result); so I'm kinda relying on external input here.

Thanks for bearing with me through this all this prose, I hope you find some time to review this issue & share your thoughts with me.
Thank you.

Cheers
Sebastian

**Comment by mcollina** [comment]
Thank you @asciidisco! Your analysis seems correct and the code sound, would you like to send a PR? Just one thing, could you add tests for this?

**Comment by asciidisco** [comment]
@mcollina Thank you for the quick response, I should be able to add the missing test cases tomorrow & to open a PR.

Just a question, as I'm not able to find some contribution information:
how would you like to have the commits sliced, everything around this fix as one single commit or changes/additions to the example and/or tests as separate commits?

**Comment by mcollina** [comment]
As many as you like, I will squash the PR into one commit when landing.
