### ISSUE TITLE
Can I use with realtime ?

### ISSUE THREAD

**Issue by lagmanzaza** [mcollina/fastify-gql#19]

**Comment by mcollina** [comment]
What do you mean?

**Comment by lagmanzaza** [comment]
I want to use graphql with graphql subscriptions so I want to know that Can I fastify-gql use with graphql subscript ?

**Comment by mcollina** [comment]
Unfortunately this feature is not supported yet.

**Comment by lagmanzaza** [comment]
Thank you sir
