### ISSUE TITLE
Cannot set a different path for playground

### ISSUE THREAD

**Issue by devotox** [mcollina/fastify-gql#194]
I have tried using 'path' & 'prefix' as I would like the playground to be on '/graphql/playground'

**Comment by mcollina** [comment]
Would you like to send a Pull Request to address this issue? Remember to add unit tests.

**Comment by GavinRay97** [comment]
You can do this with config like below:
```ts
app.register(graphql, {
  prefix: 'graphql',
  path: '/',
  ide: 'playground',
  // etc
})
```

It has a bug where the path to the GraphQL endpoint in Playground isn't right through, you need to manually correct it in the URL bar.
