### ISSUE TITLE
Error Formatting Improvements

### ISSUE THREAD

**Issue by pscarey** [mcollina/fastify-gql#196]
The `errorHandler` option controls the Fastify App Error handler directly, meaning:

- Users must fully rewrite the formatting of GraphQL errors in order to do error formatting.
- Batched query errors can't be formatted, as the overall response is a success. Errors should be formatted for each individual query, and the current implementation just sends the message of the error.

I propose a new option, `errorFormatter`. The Fastify GQL plugin will then:

- Set the app `errorHandler` using the `errorHandler` option, if provided, or if not false, set the default error handler.
- The default error handler will use either the `errorFormatter` if provided, or the default error formatter.

The `errorFormatter` option will take the form:

```js
(err: Error | GraphQLError | FastifyError) => {
    statusCode: number
    response: {
      data: object
      errors: object[]
    }
 }
```

For regular queries, the returned `statusCode` will be set, and the response will be set accordingly.
For batched queries, the `statusCode` will be ignored (set to 200) and the individual responses will be set accordingly.

An example usage of this option is:

```js
const errorParser = (e: GraphQLError) => {
    const { originalError, locations, path } = e
    const error = originalError as PlatformError

    let message
    if (error.name === 'PlatformError') {
        // Custom error formatter for internal usage
        message = getMessageForError(error.code, error.metadata)
    }

    if (!message) {
        // Error monitoring and reporting for unrecognised errors
        captureError(error)
    }

    // Default to internal server error
    return {
        message: message || 'Internal Server Error',
        locations,
        path
    }
}

const errorFormatter = (error: GraphQLServerError) => {
    if (!error.data) {
        switch (error.message) {
            // Send persisted query errors back in a formatted fashion
            case 'PersistedQueryNotFound':
                return {
                    statusCode: 200,
                    response: { data: null, errors: [{ message: 'PersistedQueryNotFound' }] }
                }
            case 'PersistedQueryNotSupported':
                return {
                    statusCode: 500,
                    response: { data: null, errors: [{ message: 'PersistedQueryNotSupported' }] }
                }
            // Send middleware errors directly
            default:
                return {
                    statusCode: error.statusCode || 500,
                    response: error.message
                }
        }
    }

    // Format all other errors as a valid GraphQL response
    const errors = (error.errors || [error]).map(errorParser)
    const data = error.data || null

    return {
        statusCode: 200,
        response: { errors, data }
    }
}
```

**Comment by pscarey** [comment]
@mcollina Happy for feedback on this - it'll be easier to see the proposed changes once we get #187 in. 

We're using this solution in production, alongside Automatic Persisted Queries, and Batched Queries, with no issues.

**Comment by aldis-ameriks** [comment]
I haven't familiarized myself with the code examples, but based on the title, I thought to plug-in my use case (wished feature) too.

I'm using type-graphql with class-validator. When combined with apollo-server, upon validation error, it spits out the following response.

```
{
  "errors": [
    {
      "message": "Argument Validation Error",
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ],
      "path": [
        "updateUserSetting"
      ],
      "extensions": {
        "code": "INTERNAL_SERVER_ERROR",
        "exception": {
          "validationErrors": [
            {
              "target": {
                "name": "some-setting",
                "value": "xxx"
              },
              "value": "xxx",
              "property": "value",
              "children": [],
              "constraints": {
                "maxLength": "value must be shorter than or equal to 2 characters"
              }
            }
          ]
        }
      }
    }
  ],
  "data": null
}
```

However, the validation error doesn't seem to be passed down within fastify-gql, even to errorFormatter.

I was thinking of tackling this one at some point later, not sure if this is within the scope of the error formatting improvements described in the issue.

**Comment by mcollina** [comment]
Thanks for taking this issue. It seems there is not a uniform way of representing errors with GraphQL as we have received a lot of contrasting issues in the past and moved the needle between a few different designs. I'm +1.

@pscarey do you think your PR could handle @aldis-ameriks case as well?

**Comment by pscarey** [comment]
I think the non-standard representation of errors has hit us too - in the above we are able to:
- Send middleware errors (e.g. authentication) directly as the appropriate status code (i.e. not as a GraphQL error).
- Send specific errors for persisted query support (also with differing status codes).
- Format known errors, so the client can use the `error.message`.
- Obfuscated unexpected errors into 'Internal Server Error'.

---

I believe that we could support @aldis-ameriks case. In my code example above, we already extract the location and paths of the error, and I think you'd just need to extract the extensions and return them, e.g.:

```js
const errorFormatter = (error: GraphQLServerError) => {
    const data = error.data || null;
    const errors = (error.errors || [error]).map((e) => {
        // Might also be worth checking e.originalError, depending on how the error is thrown
        const { extensions, locations, path, message } = e;

        // Only return specific properties of the error - further filtering of the extensions is also possible
        return { extensions, locations, path, message };
    })

    return {
        statusCode: 200,
        response: { errors, data }
    };
}
```

**Comment by aldis-ameriks** [comment]
@pscarey @mcollina 
I'm a bit confused by the presence of both `errorFormatter` and `errorHandler`.
Looking at the code, it looks like I `errorHandler` uses the `errorFormatter`, I'm a bit unsure why I would use `errorFormatter` if I could technically just use the `errorHandler` to catch and transform the error?
Maybe I'm missing something here.

**Comment by pscarey** [comment]
Hi @aldis-ameriks,

The `errorFormatter` has been implemented to allow for:
- Errors in batched queries to be formatted, as all errors are caught and formatted into an array, and the overall response is returned as success (200), regardless of the individual errors (e.g. one query might error, another might not). 
- Simpler formatting of errors which would also be raised to `errorHandler`.

**Comment by asciidisco** [comment]
@pscarey Should this explanation be added to the README maybe? I think there could be more folks who could be confused with using what & when.

**Comment by aldis-ameriks** [comment]
@pscarey Thanks. Now that there is `errorFormatter`, is there any use case where I would want to use `errorHandler` now?

**Comment by pscarey** [comment]
@asciidisco Good suggestion, thanks. I'll make an issue & look later this week.

@aldis-ameriks That very much depends on your specific use case. The `errorFormatter` option is likely sufficient for most use cases, such as:
- Handling errors from middleware (e.g. auth errors) and returning the appropriate status codes.
- Formatting GraphQL errors in order to obfuscate unknown errors ('Internal Server Error') and prettify known errors (for client rendering). 
- Formatting of persisted query errors.

If you're not using batched queries, you may want to either *continue* to use the `errorHandler` (introducing `errorFormatter` was non-breaking), or may have some special needs we've not foreseen.

@mcollina an argument could be made from this discussion to deprecate `errorHandler`, since it's an advanced use case and you can still directly override it on the Fastify instance if really essential.

**Comment by mcollina** [comment]
I think we can deprecate errorHandler and remove in a follow up
