### ISSUE TITLE
Federation: Handle situation when graphql subscribe result is not AsyncIterable.

### ISSUE THREAD

**Issue by SkeLLLa** [mcollina/fastify-gql#208]
https://github.com/mcollina/fastify-gql/blob/master/lib/subscription-connection.js#L88 

Graphql's subscribe method doesn't return AsyncIterable always. It also may return simple ExecutionResult. And if it will return it, we'll get an error.

It's pretty much the same case as in https://github.com/mcollina/fastify-gql/pull/174, when ExecutionResult just ignored.

**Comment by mcollina** [comment]
Would you like to send a Pull Request to address this issue? Remember to add unit tests.
