### ISSUE TITLE
emitWarning error when upgrading to fastify packages

### ISSUE THREAD

**Issue by simoneb** [mcollina/fastify-gql#211]
After upgrading various fastify packages the application won't start anymore due to an error being thrown:

```
TypeError: The "warning" argument must be one of type Error or string. Received type objectTypeError [ERR_INVALID_ARG_TYPE]: The "warning" argument must be one of type Error or string. Received type object

      at emitWarning (node_modules/fastify/lib/warnings.js:63:11)
      at new Parser (node_modules/fastify/lib/contentTypeParser.js:233:5)
      at ContentTypeParser.add (node_modules/fastify/lib/contentTypeParser.js:51:18)
      at Object.addContentTypeParser (node_modules/fastify/lib/contentTypeParser.js:262:30)
      at module.exports (node_modules/fastify-gql/lib/routes.js:212:7)
      at Plugin.exec (node_modules/avvio/plugin.js:129:17)
      at Boot.loadPlugin (node_modules/avvio/plugin.js:264:10)
      at release (node_modules/fastq/queue.js:127:16)
      at Object.resume (node_modules/fastq/queue.js:61:7)
```

This can be traced back to this package trying to add a content type parser with a signature that fastify considers deprecated but eventually the error is happening in Node's `process.emitWarning` because fastify is providing to it something that's not what it expects.

I tried updating all the fastify-related packages to their latest versions without any luck.

**Comment by mcollina** [comment]
This has not shipped a version compatible to fastify v3 yet :(.

**Comment by simoneb** [comment]
> This has not shipped a version compatible to fastify v3 yet :(.

Understood, yet it seems that there's an issue with how deprecation warnings are raised in fastify itself. Looking at the error above, it seems that Node breaks when fastify raises a warning.

**Comment by mcollina** [comment]
Can you open an issue in fastify itself with a small repro?

**Comment by simoneb** [comment]
I tried to reproduce it in a standalone repro but couldn't, and I figured that the warning is emitted correctly when running the app, but it crashes the process when the warning is emitted during automated tests using Jest, and the cause seems to be [this](https://github.com/facebook/jest/issues/8246#issuecomment-588345329).

**Comment by mcollina** [comment]
Closing, it's a jest problem :(.

**Comment by carvincarl** [comment]
The work-around I used is mocking process.emitWarning().
`
describe('test mock process emit warning', () => {
  let spy = null;
  beforeAll(() => {
    spy = jest.spyOn(process, 'emitWarning');
    spy.mockReturnValue('warning');
  }
  afterAll(() => {
    spy.mockRestore();
  }
  test('some library accesses a deprecated property like request.req', () => {
    // run the test
  }
}
`
