### ISSUE TITLE
Documentation for gateway

### ISSUE THREAD

**Issue by PeteSolid** [mcollina/fastify-gql#232]
Hi, I am a beginner and would like to use this with my GraphQL Endpoint from Hasura. 
How would that be possible?

**Comment by mcollina** [comment]
Hi @PeteSolid! I have never tried to use this to gateway to Hasura. Hasura does not support Federation, so maybe it's not an easy topic for a beginner. Hasura can act as a gateway itself and call your own endpoint.. it's well documented so I would recommend that.

**Comment by PeteSolid** [comment]
@mcollina Ok, many thanks. I will read through it 👍

**Comment by PeteSolid** [comment]
@mcollina One more question: is there an example / guide / tutorial to use it together with a database? For example with your repo fastify-postgres?
