### ISSUE TITLE
Slow test: test/gateway/pollingInterval.js

### ISSUE THREAD

**Issue by mcollina** [mcollina/fastify-gql#237]
This suitte is really slow: https://github.com/mcollina/fastify-gql/blob/master/test/gateway/pollingInterval.js takes up to 8 seconds on my machine. We should speed it up

cc @iviaks

**Comment by iviaks** [comment]
I will take a look at this issue :+1:

**Comment by mcollina** [comment]
Thanks!

**Comment by iviaks** [comment]
Hey, @mcollina 
.close() method from fastify takes long time

```
userService.close(): 4991.526ms
```

Can I somehow avoid this problem? like a provide a parameter for forcing, etc.
