### ISSUE TITLE
playground path does not work with custom path

### ISSUE THREAD

**Issue by gtolarc** [mcollina/fastify-gql#245]
I wish that the playground/graphiql path also works based on the custom path.
It is necessary when routing multiple services based on url path in kubernetes.

**Comment by mcollina** [comment]
Would you like to send a Pull Request to address this issue? Remember to add unit tests.

**Comment by gtolarc** [comment]
#246 If you think this is correct, it would be nice to apply this PR.
This is to avoid problems when routing other services using the same domain in kubernetes with path as a separator.

**Comment by gtolarc** [comment]
#247 It seems that the problem can be solved by combining the path/prefix option with this PR.
