### ISSUE TITLE
external subscriber

### ISSUE THREAD

**Issue by gtolarc** [mcollina/fastify-gql#249]
The current pubsub implementation cannot subscribe to multiple topics at the one subscription.
The pubsub implementation of [graphql-subscriptions](https://github.com/apollographql/graphql-subscriptions) implements its own asyncIterator to handle this.

It would be nice if we could use an external pubsub.

Maybe replacing this part with pubsub of graphql-subscriptions seems to work fine. How about? @mcollina 
https://github.com/mcollina/fastify-gql/blob/master/index.js#L121

If it's okay, it would be nice to add subscribe as an option.

**Comment by mcollina** [comment]
> The current pubsub implementation cannot subscribe to multiple topics at the one subscription.

Would you like to send a PR to add that support? It should be very simple to add.

---

Having worked _a lot_ on pubsub system and having reviewed that code, I'm not entirely comfortable in adding a dependency on graphql-subscriptions.

**Comment by gtolarc** [comment]
I just want to use the asyncIterator and withFilter implementations that are already well built in graphql-subscriptions.

Do you think it's not a good idea to allow users to choose the pubsub backend? @mcollina 
I initially thought I would simply add an option to allow the use of an external pubsub backend.

**Comment by mcollina** [comment]
> Do you think it's not a good idea to allow users to choose the pubsub backend? 

No, not really. It'd be very hard to provide a good production experience in that way.

**Comment by gtolarc** [comment]
I ported the asyncIterator of the existing graphql-subscriptions as follows, but there seems to be a problem in the part of fetching data when publishing.
Since you know the behavior of mqemitter best, it would be nice if you fix it. @mcollina 

And apart from this, if you send an object of deep-depth to the payload of publish, you got a stack error. There seems to be a problem with the readable queue processing, but I'm not sure. Obviously an error occurs.
Using graphql-subscriptions in the same logic had no problem..

And with the current structure, even if an option that allows external pubsub is added, it is not possible to use external pubsub consistently because of the difference in the context of the event msg processing method.

In my opinion, it would be better to remove the pubsub from the context, and let the user use the pubsub they want.

```javascript
'use strict'

const { $$asyncIterator } = require('iterall')
const { Readable } = require('readable-stream')

class PubSubAsyncIterator {
  constructor (pubsub, topics, queue) {
    this.pubsub = pubsub
    this.topics = topics
    this.queue = queue
    this.pullQueue = []
    this.pushQueue = []
    this.running = true
    this.allSubscribed = null
  }

  async next () {
    if (!this.allSubscribed) {
      await (this.allSubscribed = this.subscribeAll())
    }
    return this.pullValue()
  }

  async return () {
    await this.emptyQueue()
    return { value: undefined, done: true }
  }

  async throw (error) {
    await this.emptyQueue()
    return Promise.reject(error)
  }

  [$$asyncIterator] () {
    return this
  }

  async pushValue (event) {
    await this.allSubscribed
    if (this.pullQueue.length !== 0) {
      this.pullQueue.shift()(this.running ? { value: event, done: false } : { value: undefined, done: true })
    } else {
      this.pushQueue.push(event)
    }
  }

  pullValue () {
    return new Promise((resolve) => {
      if (this.pushQueue.length !== 0) {
        resolve(this.running ? { value: this.pushQueue.shift(), done: false } : { value: undefined, done: true })
      } else {
        this.pullQueue.push(resolve)
      }
    })
  }

  async emptyQueue () {
    if (this.running) {
      this.running = false
      this.pullQueue.forEach((resolve) => resolve({ value: undefined, done: true }))
      this.pullQueue.length = 0
      this.pushQueue.length = 0
    }
  }

  subscribeAll () {
    return Promise.all(
      this.topics.map((topic) => {
        this.pushValue()
        return this.pubsub.subscribe(topic, this.queue)
      })
    )
  }
}

class PubSub {
  constructor (emitter) {
    this.emitter = emitter
  }

  subscribe (topic, queue) {
    return new Promise((resolve, reject) => {
      function listener (value, cb) {
        console.log(value);
        queue.push(value.payload)
        cb()
      }

      const close = () => {
        this.emitter.removeListener(topic, listener)
      }

      this.emitter.on(topic, listener, (err) => {
        if (err) {
          return reject(err)
        }

        resolve()
      })
      queue.close = close
    })
  }

  asyncIterator (topics, queue) {
    return new PubSubAsyncIterator(this, topics, queue)
  }

  publish (event, callback) {
    this.emitter.emit(event, callback)
  }
}

// One context - and  queue for each subscription
class SubscriptionContext {
  constructor ({ pubsub, fastify }) {
    this.fastify = fastify
    this.pubsub = pubsub
    this.queue = new Readable({
      objectMode: true,
      read: () => {}
    })
  }

  subscribe (topic) {
    return this.pubsub.subscribe(topic, this.queue).then(() => this.queue)
  }

  asyncIterator (topics) {
    return this.pubsub.asyncIterator(topics, this.queue)
  }

  publish (event) {
    return new Promise((resolve, reject) => {
      this.pubsub.publish(event, (err) => {
        if (err) {
          return reject(err)
        }
        resolve()
      })
    }).catch(err => {
      this.fastify.log.error(err)
    })
  }

  close () {
    // In rare cases when `subscribe()` not called (e.g. some network error)
    // `close` will be `undefined`.
    if (typeof this.queue.close === 'function') {
      this.queue.close()
    }
    this.queue.destroy()
  }
}

module.exports = {
  PubSub,
  SubscriptionContext
}
```

**Comment by mcollina** [comment]
Can you please send a PR? I don't really understand the difference between that and what is in the repo.

---

I imagine the change to alter https://github.com/mcollina/fastify-gql/blob/60ef01f8ce82522403e6088c7dabd71e9d293bdc/lib/subscriber.js#L10 so that it calls itself multiple times for all the topics. An end user can quickly implement it as well with a `Promise.all`.

**Comment by gtolarc** [comment]
I thought asyncIterator would be good because simple iteration would be such a weird look.

```javascript
const subscription = new GraphQLObjectType({
  name: 'Subscription',
  fields: () => ({
    subscription1: {
      type,
      subscribe: async (source, args, context, info) => {
        const s = await Promise.all(
          ['TOPIC1', 'TOPIC2'].map((topic) => context.pubsub.subscribe(topic))
        );
        return s[0];
      },
```

And there are cases when publishing to pubsub outside of fastify. Wouldn't it be better to just separate pubsub for this case?

**Comment by gtolarc** [comment]
In fact, I am using graphql-subscriptions as a standalone pubsub with fastify-gql. The pubsub of the internal context is a burden.

**Comment by gtolarc** [comment]
#256
