### ISSUE TITLE
Instructions on using with SubscriptionServer (subscriptions-transport-ws)

### ISSUE THREAD

**Issue by laurisvan** [mcollina/fastify-gql#257]
First of all, thanks for the great work this far - I have been almost able to migrate our largish apollo-server project to fastify-gql. Currently we face hurdles in getting subscriptions working. Our previous implementation relies on Apollo SubscriptionServer (https://github.com/apollographql/subscriptions-transport-ws) which we took into use as that plays well together with graphql-modules. We did not take fastify-websocket into use, as I understood SubscriptionServer would play that part.

The current documentation is a bit murky on how fastify-qgl subscriptions actually work. As the Apollo SubscriptionServer is likely the first implementation many consider, would it be possible to provide an example of getting it to work?

My current bits of code go as follows (:

`
import { execute, subscribe } from 'graphql'
import { GraphQLModule } from '@graphql-modules/core'
import { SubscriptionServer } from 'subscriptions-transport-ws'
import fastify, { FastifyInstance, FastifyRequest, FastifyReply, FastifyError, HookHandlerDoneFunction } from 'fastify'
import fastifyGql from 'fastify-gql'

   ... (a lot of code likely not relevant)

    await app.register(fastifyGql as any, {
      // errorHandler: this.handleGraphQLError.bind(this),
      ide: 'playground',
      path: APIService.GRAPHQL_PATH,
      schema: appModule.schema,
      context: APIService.createContext,
      subscription: subscribe
    })

    const subscriptionServer = SubscriptionServer.create({
      schema: appModule.schema,
      execute,
      subscribe,
      // Note: appModule holds onConnect, onDisconnect etc.. hooks
      ...appModule.subscriptions
    },
    {
      server: app.server,
      path: APIService.GRAPHQL_PATH
    })

    app.listen(this.port, (err, address) => {
      if (err) {
        throw err
      }
      console.log(`${this.prefix} HTTP server at http://localhost:${this.port}${APIService.GRAPHQL_PATH}`)
      console.log(`${this.prefix} WS server at http://localhost:${this.port}${APIService.GRAPHQL_PATH}`)
    })
    this.server = app`

**Comment by mcollina** [comment]
I have no tested this particular combination, nor I know how to make that work.

**Comment by laurisvan** [comment]
Ok, it appears the whole SubscriptionServer can be skipped by just using PubSub as in #195 . This issue can be closed. 

I got another problem - exposing websocket payload when creating context for web sockets. It appears this is the mechanism used e.g. by GraphQL Playground (and our app, too). I vaguely remember there was a reason for doing it so. The README sample shows how to expose it from within the request headers, but I believe most clients will not send in handshake message payload, instead.

@mcollina I think it were trivial to expose the payload (I checked from debugger that it available deeper in stack trace - would you accept a PR if I supplemented the payload into the calls as follows:

`
app.register(GQL, {
  schema,
  resolvers,
  subscription: {
      // Expose the payload to context creation
      context: (_, req, payload) => ({ user: jwt.verify(payload["Authorization"].slice(7))})
  }
})
`

**Comment by mcollina** [comment]
what do you mean by payload?

**Comment by laurisvan** [comment]
I meant the web socket data frame. However, I did a bit of investigation and noticed that onConnect receives that, and the output of onConnect() and context() calls get merged. So, no changes are needed to the API

I could supply a bit to the docs to explain this a bit better, so that the others do not need to do this research again.
