### ISSUE TITLE
[Playground] set header and dark theme setting

### ISSUE THREAD

**Issue by saostad** [mcollina/fastify-gql#272]
hi,
is there any way to set Http headers in the playground?
also, is there any way to change the default light theme to a dark theme?

**Comment by asciidisco** [comment]
I guess you're referring to the settings mentioned here: https://github.com/prisma-labs/graphql-playground#settings

There's currently no way to do this via the `fastify-gql` settings; channeling my inner @mcollina here, leads to the question:
"would you like to send a PR to fix/improve this?"

There are basically 2 code parts you would need to spend your attention on, if you'd like to integrate this:

https://github.com/mcollina/fastify-gql/blob/master/index.js#L196
https://github.com/mcollina/fastify-gql/blob/master/lib/routes.js#L307

**Comment by blimmer** [comment]
Is this fully implemented as part of 5.7.0? The type definitions don't seem to support `playgroundOptions` as of 5.7 for me.

**Comment by mcollina** [comment]
I think the types just need to be updated, want to send a PR?

**Comment by blimmer** [comment]
@mcollina Yep, no problem. See #285.
