### ISSUE TITLE
How do I use fastify-gql with TypeScript type safety

### ISSUE THREAD

**Issue by nabsofken** [mcollina/fastify-gql#281]
I wanted to use TypeScript but I am having issues updating my resolvers arguments with types. E.g. whats is the type for the object, argument, context, info arguments?

**Comment by mcollina** [comment]
I'm not a typescript user and I can't really help.

**Comment by PabloSzx** [comment]
Now we have official docs about TypeScript usage https://mercurius.dev/#/docs/typescript 🎉
