### ISSUE TITLE
Using request in resolver

### ISSUE THREAD

**Issue by Tarang11** [mcollina/fastify-gql#33]
Is there any way to use request inside resolver.

**Comment by mcollina** [comment]
request as in the npm module? what’s stopping you from using it?

**Comment by PacoDu** [comment]
I think @Tarang11 is referring to the fastify Request object that is not bound to the resolver context (only app and res are shared to the resolver context). I also faced this issue while developing this fastify-gql

**Comment by mcollina** [comment]
Can you send a PR? Or at least make a full example?

**Comment by Tarang11** [comment]
fastify request object

**Comment by mcollina** [comment]
Can you make a full example? I think this is _already_ supported.

I think you can do `context.reply.request` to access the request. Unfortunately that field is not documented in fastify itself (https://github.com/fastify/fastify/blob/356cf6f078a9f93b009ddb6384deaffe549d1032/lib/reply.js#L61).

**Comment by Tarang11** [comment]
Thanks, this solved the problem, but without documentation this is bit cryptic.

**Comment by mcollina** [comment]
@Tarang11 would you like to send a PR and maybe add a unit test as well?

**Comment by Tarang11** [comment]
PR for documentation?

**Comment by mcollina** [comment]
Yes

**Comment by Tarang11** [comment]
sure

**Comment by john-behan** [comment]
@mcollina can this be closed now?

**Comment by mcollina** [comment]
Yes!!
