### ISSUE TITLE
Proposal: fastify.graphql.setSchema() function

### ISSUE THREAD

**Issue by bompus** [mcollina/fastify-gql#38]
I would like to propose fastify.graphql.setSchema() , something like:

```js
fastifyGraphQl.setSchema = function(s) {
    if (typeof s === 'string') {
      schema = buildSchema(s)
    } else {
      schema = s;
    }

    // we should clear the caches, because they could be totally invalid now
    lru.clear();
    lruErrors.clear();
  }
```

My use case is an admin dashboard that allows adding/updating/deleting fields from types, as well as adding/deleting types.

I believe this function would allow me to make a change in my admin dashboard, call setSchema(), and then without re-starting the app, my graphql route would be utilizing the new schema.

I'd be willing to submit a PR with test and README updated if this is something that you think would be useful to the general community.

**Comment by mcollina** [comment]
I'm not really understanding how that plugin would be supposed to work. Specifically:

1. where would you store the schema
2. what will be your resolvers, as currently those needs to be defined in code

The general approach in Fastify is "build once and then reuse", as making things updatable at runtime is going to add complexity and slow things down.

**Comment by bompus** [comment]
In my case, the schema would be generated based on a MongoDB schema, and on app startup, would generate the graphql schema.

The resolvers would also be generated on app startup based on this.

It's an odd idea, but I think it would be very powerful if it works as I have it envisioned.

This is part of the discussion in regards to if it fits in well with the fastify-gql plugin and ecosystem. If you think it's a bad or weird idea, I'm fine with running my own fork of the plugin for now to see how the idea pans out.

**Comment by mcollina** [comment]
I would recommend against it. Putting applicaiton logic in a database is an anti-pattern, and it will make it hard to migrate it between various environment. You are going to end up in trouble because the resolvers will likely require indexes in the databases and similar features. In other terms, making this work effectively requires _a lot_ of work on the side.

It probably better that you live with your own fork for now, and maybe we can land it in the future.
