### ISSUE TITLE
validationRules ??

### ISSUE THREAD

**Issue by blacksmoke26** [mcollina/fastify-gql#40]
I want to use [graphql-cost-analysis](https://github.com/pa-bru/graphql-cost-analysis), So my question is how can I use that one because it requires `validationRules` property.

Any clue?

**Comment by blacksmoke26** [comment]
`validationRules` something like:
https://github.com/graphql/express-graphql/blob/master/src/index.js#L254

**Comment by mcollina** [comment]
Would you like to send a PR?

**Comment by blacksmoke26** [comment]
Yeah for sure. I have solved that myself, I think it's time to create a Pull Request.

Thanks

**Comment by aldis-ameriks** [comment]
I believe this is similar to #188 which was resolved via #189 and #193. In which case the issue could be closed.
