### ISSUE TITLE
Enrich context

### ISSUE THREAD

**Issue by firasdib** [mcollina/fastify-gql#47]
Is it possible to enrich the context thats being sent to the resolvers?

Perhaps through a function that you supply when creating the instance, something like this:

```
app.register(GQL, {
  schema,
  resolvers,
  context: (request, reply) => ({ foo: true }),
});
```

**Comment by mcollina** [comment]
This is already supported via the reply decorators.
Essentially the context already include the `reply` object, and so adding any decorator there will be populated.

If you are thinking about something else, feel free to raise a PR - it's a valuable feature.

**Comment by asciidisco** [comment]
@mcollina As this seems to be stale & the status of https://github.com/mcollina/fastify-gql/pull/153 is tracked in #151 I think it can be closed. You're with me on this?
