### ISSUE TITLE
Add typescript typings

### ISSUE THREAD

**Issue by SkeLLLa** [mcollina/fastify-gql#48]
In order to use this package with typescript it requires proper typings.

I've made some progress, however I've find out that for now it's not possible. That's because now in fastify typings plugin `RegisterOptions` extend `RouteShorthandOptions` for some reason not known to me. `RouteShorthandOptions` however contains `schema` field that has type `RouteSchema` that's obviously incompatible with the same field `schema` in this module which could be either string or GraphQLSchema.

Typescript allows to redefine `RouteShorthandOptions` with additional types for `schema`, but it will affect all routes. So I think we should wait for https://github.com/fastify/fastify/pull/1569 to be merged. Or if you have any other suggestions, you're welcome.

**Comment by Ethan-Arrowood** [comment]
Yeah the current typings are very limited. I'd be happy to help out with making this work with v3 types. Let me know if you have any questions!
