### ISSUE TITLE
Add graphql playground alongside with graphiql

### ISSUE THREAD

**Issue by SkeLLLa** [mcollina/fastify-gql#52]
Hi. There's graphql playground that does pretty much the same things that graphiql does. However it has more features. Here's demo page: https://www.graphqlbin.com/v2/6RQ6TM

It has standalone package https://www.npmjs.com/package/graphql-playground-html that contains several html files https://github.com/prisma/graphql-playground/tree/master/packages/graphql-playground-html that could be used just like as graphiql.html. We could copy one of them into static folder just like it's done in fastify-swagger plugin.

Also it doesn't use service worker which allows to explore it without having https (e.g. on some domain like example.loc that will point to 127.0.0.1). In such case graphiql doesn't work.

I could send PR with this changes, but I need a suggestion which route it should expose: `/gql-playground` or `graphiql-playground` or something else.

**Comment by mcollina** [comment]
That'd be amazing, yes. I'd prefer if we didn't increase the size of this module, and maybe load the playground via unpkg, is that possible?

**Comment by SkeLLLa** [comment]
@mcollina it's only one html file that loads all other stuff from CDN. We could copy only this file https://github.com/prisma/graphql-playground/blob/master/packages/graphql-playground-html/withAnimation.html and that's all.

**Comment by mcollina** [comment]
+1, ok

Il giorno mer 15 mag 2019 alle ore 14:06 Alexander Kureniov <
notifications@github.com> ha scritto:

**Comment by SkeLLLa** [comment]
@mcollina what route name do you suggest for that playground?
