### ISSUE TITLE
How To Add preHandler For /graphql and /graphiql

### ISSUE THREAD

**Issue by naseemali925** [mcollina/fastify-gql#60]
I have been trying to protect the following route
/graphql
/graphiql

How can this be done?

**Comment by mcollina** [comment]
You'd need to add a fastify hook to validate your credentials.
I would use the `'preParsing'` hook. https://www.fastify.io/docs/latest/Hooks/

Check out https://github.com/fastify/fastify-jwt

**Comment by naseemali925** [comment]
Thanks, @mcollina I Will Try. I Guess the preParsing Would Be Executed For Each Route That's There In The App. I am actually looking for a hook that executes only when a certain route is requested. For example
/api/v1/users

With the preParsing Hook i cannot limit it to only part of the url "/api/v1"
Any advice would be a great help. 
Thanks,

**Comment by mcollina** [comment]
You should just wrap your `/api/v1` in a plugin together with fastify-gql, and add the hooks there.

**Comment by naseemali925** [comment]
Thanks for the help @mcollina I will try.

**Comment by naseemali925** [comment]
@mcollina Wrapping It Inside The Plugin Did The Trick. Thanks For All The Help.
