### ISSUE TITLE
Subcription support

### ISSUE THREAD

**Issue by mcollina** [mcollina/fastify-gql#67]
It would be good to have some level of _optional_ subscription support on top of fastify-gql, maybe using https://github.com/fastify/fastify-websocket.

https://github.com/graphql/graphql-spec/blob/master/rfcs/Subscriptions.md is the definition of subscriptions.

For the pub/sub layer, I'd recommend using https://github.com/mcollina/mqemitter as it has 2 backend implementations (one with Redis and one with MongoDB).

**Comment by wtrocki** [comment]
Linked to spectrum:
https://spectrum.chat/apollo/subscriptions/how-to-setup-apollo-server-fastify-to-have-subscriptions-working~631caa9c-e193-4ecb-ae62-edfb1158c22b

**Comment by mcollina** [comment]
Implemented in #78
