### ISSUE TITLE
Depth limit for Fastify-GQL

### ISSUE THREAD

**Issue by john-behan** [mcollina/fastify-gql#68]
This plugin for express-graphql and koa-graphql address the issue of depth limiting graphql queries - https://github.com/stems/graphql-depth-limit to help with the problem of depth limiting

The rationale is explained in the readme - https://github.com/stems/graphql-depth-limit#why

This is probably only really an issue for public APIs but perhaps we could implement a fastify-gql version of this plugin or raise a pr on that one to add support for fastify-gql

**Comment by mcollina** [comment]
I would prefer if this got added to to fastify-gql as a first-class concept.

**Comment by john-behan** [comment]
I've started looking more closely. I propose this as an approach - 

On the fastify-gql options object we enable a `depthLimit` property, the value will represent the limit on recursive queries. There is an issue with this though - what if we want to allow different limits for different queries? Perhaps the value of the `depthLimit` option could then be something like `{ queryName: queryDepthLimit, .... }`

The plugin https://github.com/stems/graphql-depth-limit uses the validationRules param of an express-graphql query to reject or allow a query based on the query depth. We could use something similar - analyse a query and if it breaks the query depthLimit rule it is rejected.

**Comment by mcollina** [comment]
I see this as a settings that should be applied to the whole `graphql`  plugin.
I'll add the depth validation logic after this line: https://github.com/mcollina/fastify-gql/blob/bb9eb706648135637e442239bcc71492da46b13d/index.js#L222.

**Comment by john-behan** [comment]
I'll put something together in a branch
