### ISSUE TITLE
Add examples for using subscriptions

### ISSUE THREAD

**Issue by mcollina** [mcollina/fastify-gql#81]
With:

* [ ] redis https://github.com/mcollina/mqemitter-redis
* [ ] mongodb https://github.com/mcollina/mqemitter-mongodb
* [ ] cluster/multiple process on the same machine https://github.com/mcollina/mqemitter-child-process

**Comment by santiagoalmeidabolannos** [comment]
looks like there is a redis example in the Readme file, are you looking for something different?

**Comment by mcollina** [comment]
I think this is done
