### ISSUE TITLE
Error path static. Please check, there should be a step up one level.

### ISSUE THREAD

**Issue by StrongerMyself** [mcollina/fastify-gql#82]
https://github.com/mcollina/fastify-gql/blob/65e25ab638b97fa354993e1d1b35caa320af9aba/lib/routes.js#L196

**Comment by StrongerMyself** [comment]
`root: join(__dirname, '../static'),`

**Comment by mcollina** [comment]
Can you send a PR?

Il giorno gio 31 ott 2019 alle 14:40 StrongerMyself <
notifications@github.com> ha scritto:

**Comment by StrongerMyself** [comment]
https://github.com/mcollina/fastify-gql/pull/83

**Comment by mcollina** [comment]
Thanks! Released as 2.0.1
