### ISSUE TITLE
Caching query results?

### ISSUE THREAD

**Issue by GimignanoF** [mcollina/fastify-gql#88]
I'm using the fastify-caching npm package to cache requests, however large queries still takes 300ms to return to client, where the same query with express and memory-cache package take around 60 after being cached. So how can i efficiently cache the query results with fastify? :)

**Comment by mcollina** [comment]
This module does not set any caching headers, so fastify-caching behavior does not kick in.
I'm not really convinced that using HTTP caching with GraphQL is a good idea overall, and I've never investigated it.

Anyway, would you like to send a PR to add an option to set the right caching headers for GET requests? Thanks

**Comment by GimignanoF** [comment]
Why that wouldn't be a good idea? Maybe persisted queries would be the way to go? Anyway I'll see if i can do a PR any time soon ;)

**Comment by mcollina** [comment]
Because each resolver could potentially need different caching strategy.
Il 25 nov 2019, 09:17 +0100, Jimi <notifications@github.com>, ha scritto:

**Comment by ericlewis** [comment]
I would recommend this be closed, the reasoning for not implementing caching in this regard is similar to why you would cache an api that takes something like: `query=1,2,3,4` then `query=1,4`.

**Comment by mcollina** [comment]
Thanks!

**Comment by ColeTownsend** [comment]
Is this something the team would consider revisiting? [Apollo Server](https://www.apollographql.com/docs/apollo-server/performance/caching/) has some decent examples using directives.
