### ISSUE TITLE
Graphiql page isn't rendering

### ISSUE THREAD

**Issue by thesrs02** [mcollina/fastify-gql#89]
Just installed Fastify GQL and I can't seem to render the Graphiql interface / page on localhost. 

- Tried setting routes to true / false
- Tried the example -- didn't work

**Index.js**
![image](https://user-images.githubusercontent.com/37621213/69588014-27ff1500-1009-11ea-9383-bbb066905448.png)

**Browser:**
![image](https://user-images.githubusercontent.com/37621213/69588050-4402b680-1009-11ea-87af-63c0e1fbe431.png)

**Package.json:**
![image](https://user-images.githubusercontent.com/37621213/69587804-84ae0000-1008-11ea-8814-f3dfc329a74f.png)

Pretty basic stuff but can't seem to get it to work - maybe I'm missing something and I would appreciate the help.

Thanks!

**Comment by mcollina** [comment]
GraphiQL is available at GET /graphiql (or GET /graphql)

You do not need to use `app.graphql`, you can just send your GraphQL queries to `/graphql`.

**Comment by thesrs02** [comment]
Didn't work - getting a different error message now.

Route: http://localhost:3000/graphql
Response: 404 - {"errors":[{"message":"Must provide Source. Received: undefined"}]}
Node V: v12.13.0

**Comment by mcollina** [comment]
Run https://github.com/mcollina/fastify-gql/blob/master/examples/basic.js

and go to /graphiql

**Comment by Weakky** [comment]
Since 3.0.3, it seems like `graphiql: true` doesn't work anymore, and so does the examples. Instead, `ide: 'graphiql'` seems to do the job.
