### ISSUE TITLE
GQL Mutation - Receiving unexpected "[Object: null prototype]"

### ISSUE THREAD

**Issue by thesrs02** [mcollina/fastify-gql#90]
Sending payload in Mutation also returns this "[Object: null prototype]" as a reference key for the actual payload - seems to be a bug.

**Error**: 
![image](https://user-images.githubusercontent.com/37621213/69900140-cab0ee00-1391-11ea-8575-e042d4fe915b.png)

**Workaround:** 
`JSON.parse(JSON.stringify(payload))`

**Reproduce**:
server.js config for GQL Fastify
```
app.register(GQL, {
  schema: makeExecutableSchema({typeDefs, resolvers})
});
```

**Resolver**
```
Mutation: {
    createUser: async (_, {payload}) => {
      console.log(payload);
    }
  }
```

**TypeDefs / Schema**

```
		type User {
			id: ID
			firstName: String
			lastName: String
			username: String
			email: String
			avatar: String
			birthDate: Float
			startDate: Float
		}

		input UserInput {
			id: ID
			firstName: String!
			lastName: String!
			username: String
			email: String!
			avatar: String
			birthDate: Float
			startDate: Float
		}

		type Query {
			getOneUser(id: ID!): User
	  }

		type Mutation {
			createUser(payload: UserInput): User
		}

```
**Mutation Query**
```
mutation {
  createUser(payload:{
      id: "52jk452k3j452jk3452k3452345kjfac",
      firstName: "Rehan",
      lastName: "Haider",
      username: "rehanhaider",
      email: "thesrs02@gmail.com",
      avatar: "https://tinyurl.com/qsqau3r",
      birthDate: 41234123412341,
      startDate: 41234123412344
    }) {
    firstName
    lastName
    lastName
    username
    email
    avatar
    birthDate
    startDate
  } 
}
```

Might be similar to this: https://github.com/apollographql/apollo-server/issues/3149

Let me know if more details are required.

**Comment by mcollina** [comment]
It would be good to get a full example to reproduce.
Moreover, if you'd like to send a PR with a fix, It would be fantastic.

**Comment by thesrs02** [comment]
Okay so the prototype is not related to GraphQL or Fastify-GraphQL. It comes from Node and I don't think they're changing it anytime soon. Ref: https://github.com/nodejs/node/issues/30183

After spending 2+ hours, I've found and tested that it just adds verbosity and doesn't actually cause any harm.

Fastify:
![image](https://user-images.githubusercontent.com/37621213/69903825-a15b8680-13c0-11ea-8171-fe99f9fd08b4.png)

Not a big issue and workarounds are available so closing now.
