### ISSUE TITLE
graphiql & graphql-playground accessible simultaneously

### ISSUE THREAD

**Issue by feugy** [mcollina/fastify-gql#92]
Hi there!

This is a very minor issue, but I've been puzzled as you can access both `graphiql.html` and `playground.html` as soon as you define `graphiql` configuration key (as long as it is not falsy).

The reason is because the two files are served from the static folder:
https://github.com/mcollina/fastify-gql/blob/ca23bb6c22d88b021a4b4503cfae321895e5dc8d/lib/routes.js#L190-L205

So when `graphiql` key is 
- `true` or `'graphiql'`: you have access to `/graphiql` and `/playground.html`
- `'playground'`: you have access to `/graphiql.html` and `/playground`

This is not really an issue, more an improvement.

**Comment by mcollina** [comment]
Thanks!
