### ISSUE TITLE
Poor latency?

### ISSUE THREAD

**Issue by deklanw** [mcollina/fastify-gql#95]
Just based on the benchmarks here,

https://github.com/the-benchmarker/graphql-benchmarks/blob/develop/latency.md

I noticed that both frameworks using Fastify have high latency, especially fastify-gql. Is there some bias in the benchmark? Or, is this a limitation of fastify-gql? 

Thanks

**Comment by mcollina** [comment]
I’m not entirely sure what’s happening. It would be interesting to debug and verify where we are losing latency.

I would recommend the benchmark methodology to pre-heat all the JS implementation, as it takes some time for V8 to optimize.

I would also recommend to use the data loader pattern for finds and enable the jit option in fastify-gql.

**Comment by deklanw** [comment]
> I would recommend the benchmark methodology to pre-heat all the JS implementation, as it takes some time for V8 to optimize.

The test appears to run for 20 seconds. Is that not sufficient?

> I would also recommend to use the data loader pattern for finds and enable the jit option in fastify-gql.

None of the other implementations use a dataloader pattern. I'm not sure if that would be a fair comparison.

Would setting the `jit` option to something like `1` or `2` suffice?

**Comment by mcollina** [comment]
> The test appears to run for 20 seconds. Is that not sufficient?

Run it twice, and take the second set of measurements. In my tests, 40 seconds provide more stable results.

> Would setting the jit option to something like 1 or 2 suffice?

yes, that’d be ok.

**Comment by SkeLLLa** [comment]
Probably that "latency" stuff somehow related to this lines of code in benchmark: https://github.com/the-benchmarker/graphql-benchmarks/blob/develop/frameworks/fastify-gql/app.js#L72.

I don't know what's there latency shows, but here some of my results with k6:

**Comment by mcollina** [comment]
It seems totally ok from your diagram.

**Comment by deklanw** [comment]
@SkeLLLa 

I was actually wondering if there were alternative benchmarks of fastify-gql I could look at. (Is there any more?) Thank you. That's interesting. What kind of data is going through there?

I notice `http_req_duration` max for JIT and non-JIT respectively: `1.01s` `807.95ms`. Everything else seems faster for JIT. The max and 95th percentile seem extremely disparate. Is this some database cache warming up or something?

**Comment by SkeLLLa** [comment]
@deklanw That "max" duration is caused because data is fetched from 3rd-party server. And it cause this "max" value. Later those values are cached for some time and we see performance of fastify-gql. 

Data is ~1Kb with nested arrays and objects + couple data loaders.

As for other frameworks benchmarks - I just have my server and run benchmarks on it. And it's written using fastify-gql.

**Comment by deklanw** [comment]
Got PR merged with `jit` enabled over on the benchmark. Rate and latency improved. And, anyway, I was misreading those rates as being in seconds not milliseconds. Silly! Comparing subms benchmarks is of course silly

Thanks for the help
